/*
 * Regenerates src/emojiData.ts from the emoji-datasource package.
 *
 *   npm run generate-emoji
 *
 * The result is committed so the published package carries no emoji dependency
 * and builds are reproducible. CI fails if the committed file drifts.
 */

import { createRequire } from 'node:module'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

interface RawEmoji {
  short_name: string
  short_names: string[]
  unified: string
}

const require = createRequire(import.meta.url)
const rawEmoji = require('emoji-datasource/emoji.json') as RawEmoji[]
const { version } = require('emoji-datasource/package.json') as { version: string }

const shortNameToUnified = new Map<string, string>()
for (const emoji of rawEmoji) {
  // The primary shortname wins any collision with another entry's alias.
  shortNameToUnified.set(emoji.short_name, emoji.unified)
}
for (const emoji of rawEmoji) {
  for (const shortName of emoji.short_names) {
    if (!shortNameToUnified.has(shortName)) {
      shortNameToUnified.set(shortName, emoji.unified)
    }
  }
}

const sorted = [...shortNameToUnified].sort(([a], [b]) => (a < b ? -1 : 1))
const entries = sorted
  .map(([shortName, unified]) => `  ${JSON.stringify(shortName)}: '${unified}',`)
  .join('\n')

const contents = `// Generated by scripts/generateEmoji.ts. Do not edit by hand.
// Source: emoji-datasource@${version}
//
// Maps a Slack emoji shortname to its dash-separated Unicode code points.

export const emojiData: Readonly<Record<string, string>> = {
${entries}
}
`

const outputPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'emojiData.ts')
writeFileSync(outputPath, contents, 'utf8')
console.log(`Wrote ${sorted.length} emoji shortnames from emoji-datasource@${version}`)
